# Generated by Django 5.0 on 2024-01-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=500)),
                ('prop', models.CharField(max_length=500)),
                ('acts_as_nr', models.IntegerField()),
                ('acts_as_letter', models.CharField(max_length=3)),
            ],
        ),
    ]
