# Generated by Django 5.0 on 2024-01-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0003_remove_actor_acts_as_letter_remove_actor_acts_as_nr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='contains_letters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cast',
            name='contains_numbers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='contains_symbols',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cast',
            name='encoding_steps',
            field=models.IntegerField(default=3),
        ),
    ]
